version: '2'
services:
  excavator:
    env_file:
      - .env
    build:
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "run", "excavator"]
