version: '2'
services:
  shovel:
    env_file:
      - .env
    build:
      args:
        - secret=${SECRET}
      context: .
      dockerfile: Dockerfile.shovel
    command: ["yarn", "run", "shovel"]
