version: '2'
services:
  excavator:
    env_file:
      - .env
    build:
      args:
        - secret=${SECRET}
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "run", "excavator"]
